services:
  db:
    image: postgres:14
    env_file:
      - app/core/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: .
    restart: always
    env_file:
      - app/core/.env
    container_name: tnt_app
    ports:
      - 9999:8000
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network:
    driver: bridge
